<?php

namespace Database\Seeders;

use App\Models\Clothe\Clothe;
use App\Models\User\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class ClothesSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::query()->first();

        $clothes = [
            [
                'uuid' => '01K7VAHHAZXMQ9GESA1B51TZEA',
                'user_id' => $user->id,
                'label' => 'Relaxed Fit Denim Chore Jacket',
                'category' => 'outerwear',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#3A638B', 'secondary' => '#6B6A56']),
                'source_path' => 'source/1/44b3f8e3-1b23-4043-b942-115c94e5995e.png',
                'image_path' => 'wardrobe/1/1.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A versatile relaxed-fit denim chore jacket, perfect for adding a touch of casual cool to any outfit, featuring a quilted lining for added warmth and comfort.', 'materials' => ['denim', 'cotton']]),
                'metadata' => json_encode(['fit' => 'relaxed', 'pattern' => 'solid', 'care' => 'Machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:31:19',
                'updated_at' => '2025-10-18 09:31:19',
            ],
            [
                'uuid' => '01K7VAJ86YENDSY7WVR6FNAYEH',
                'user_id' => $user->id,
                'label' => 'Trekking Style Suede Sneakers',
                'category' => 'shoes',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#C2B280', 'secondary' => '#D3A9A9']),
                'source_path' => 'source/1/0fd9b672-b83d-4868-a702-c0189a2fda02.png',
                'image_path' => 'wardrobe/1/2.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Step out in style and comfort with these trekking-inspired suede sneakers, perfect for everyday adventures. Their robust design offers both durability and a fashionable edge.', 'materials' => ['suede', 'rubber']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'Wipe clean with a damp cloth', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:31:43',
                'updated_at' => '2025-10-18 09:31:43',
            ],
            [
                'uuid' => '01K7VAK5Y1FKCKHVM5W47VPSEZ',
                'user_id' => $user->id,
                'label' => 'Oversized Graphic Hoodie',
                'category' => 'top',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#F8F8F8', 'secondary' => '#F0B6C0']),
                'source_path' => 'source/1/78dd721a-e413-4001-8cbc-416564bb4234.png',
                'image_path' => 'wardrobe/1/3.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'This oversized hoodie offers ultimate comfort and a relaxed style, featuring a subtle graphic print on the chest. Perfect for a laid-back look.', 'materials' => ['cotton blend']]),
                'metadata' => json_encode(['fit' => 'oversized', 'pattern' => 'graphic', 'care' => 'machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:32:13',
                'updated_at' => '2025-10-18 09:32:13',
            ],
            [
                'uuid' => '01K7VAKQPPCMR5BVTK71NMWBF3',
                'user_id' => $user->id,
                'label' => 'Hooded Puffer Jacket',
                'category' => 'outerwear',
                'occasion' => 'casual',
                'season' => 'winter',
                'color_palette' => json_encode(['primary' => '#EBE8E3']),
                'source_path' => 'source/1/4c8d1a00-3b95-4284-b7f4-9eb64a283c32.png',
                'image_path' => 'wardrobe/1/4.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Stay warm and stylish in this versatile hooded puffer jacket, perfect for chilly weather. Its cozy design ensures comfort without compromising on modern aesthetic.', 'materials' => ['polyester', 'down filling']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'machine wash cold, tumble dry low', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:32:31',
                'updated_at' => '2025-10-18 09:32:31',
            ],
            [
                'uuid' => '01K7VAMC9CHPXRRDBJ4QHAW1QQ',
                'user_id' => $user->id,
                'label' => 'Oversized Faux Leather Bomber Jacket',
                'category' => 'outerwear',
                'occasion' => 'casual',
                'season' => 'autumn',
                'color_palette' => json_encode(['primary' => '#1A1A1A']),
                'source_path' => 'source/1/5db317a4-58ca-4624-9b06-6bae62369f9c.png',
                'image_path' => 'wardrobe/1/5.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'This oversized faux leather bomber jacket offers a contemporary and edgy look with a relaxed fit. Perfect for adding a stylish layer to your casual outfits.', 'materials' => ['faux leather', 'polyester']]),
                'metadata' => json_encode(['fit' => 'oversized', 'pattern' => 'solid', 'care' => 'wipe clean', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:32:52',
                'updated_at' => '2025-10-18 09:32:52',
            ],
            [
                'uuid' => '01K7VAT7JYP2B8GWRMVQYWZATC',
                'user_id' => $user->id,
                'label' => 'Daniel Wellington Quadro Pressed Sheffield Watch',
                'category' => 'accessory',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#000000', 'secondary' => '#FFFFFF']),
                'source_path' => 'source/1/4612f8ea-0d68-4ae1-9ce9-54dbdd522be5.png',
                'image_path' => 'wardrobe/1/6.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'This elegant timepiece features a rectangular gold-toned case, a crisp white dial, and a classic black leather strap, perfect for adding a sophisticated touch to any outfit.', 'materials' => ['stainless steel', 'leather']]),
                'metadata' => json_encode(['fit' => 'null', 'pattern' => 'solid', 'care' => 'Wipe clean with a damp cloth', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:36:04',
                'updated_at' => '2025-10-18 09:36:04',
            ],
            [
                'uuid' => '01K7VB0H868D6G06QY2EN4GB02',
                'user_id' => $user->id,
                'label' => 'Daily Vibe Embroidered Baseball Cap',
                'category' => 'accessory',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#5C3E34', 'secondary' => '#FFFFFF']),
                'source_path' => 'source/1/654e03d1-a8f2-496e-ae2b-921019d4003d.png',
                'image_path' => 'wardrobe/1/7.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Embrace comfort and style with this everyday baseball cap, featuring \'DAILY VIBE\' embroidery for a relaxed yet fashionable look.', 'materials' => ['cotton blend']]),
                'metadata' => json_encode(['fit' => 'null', 'pattern' => 'graphic', 'care' => 'spot clean', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:39:31',
                'updated_at' => '2025-10-18 09:39:31',
            ],
            [
                'uuid' => '01K7VB0ZEP02XYEMHHG6P6EWCS',
                'user_id' => $user->id,
                'label' => 'Untitled garment',
                'category' => null,
                'occasion' => null,
                'season' => null,
                'color_palette' => null,
                'source_path' => 'source/1/9c45ff94-a1b2-4fde-b2d3-f2c83b191c58.png',
                'image_path' => 'wardrobe/1/8.png',
                'thumbnail_path' => null,
                'ai_summary' => null,
                'metadata' => json_encode(['fit' => null, 'pattern' => null, 'care' => null, 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:39:45',
                'updated_at' => '2025-10-18 09:39:45',
            ],
            [
                'uuid' => '01K7VB1N0RDGR5QBKWT99Q7425',
                'user_id' => $user->id,
                'label' => 'Curved Frame Dark Lens Sunglasses',
                'category' => 'accessory',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#1A1A1A']),
                'source_path' => 'source/1/97bebe9f-9884-49fd-b618-52e4a4631d12.png',
                'image_path' => 'wardrobe/1/9.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'These stylish sunglasses feature a unique curved frame and dark lenses, perfect for adding a touch of modern flair to any casual outfit.', 'materials' => ['plastic', 'polycarbonate']]),
                'metadata' => json_encode(['fit' => null, 'pattern' => 'solid', 'care' => 'Wipe clean with a soft cloth', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:40:07',
                'updated_at' => '2025-10-18 09:40:07',
            ],
            [
                'uuid' => '01K7VBC21A77GQNJQ5J9HWCZDQ',
                'user_id' => $user->id,
                'label' => 'Untitled garment',
                'category' => null,
                'occasion' => null,
                'season' => null,
                'color_palette' => null,
                'source_path' => 'source/1/09f0ed1e-1223-40a3-b4b3-4c77c72eb27b.png',
                'image_path' => 'wardrobe/1/10.png',
                'thumbnail_path' => null,
                'ai_summary' => null,
                'metadata' => json_encode(['fit' => null, 'pattern' => null, 'care' => null, 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:45:48',
                'updated_at' => '2025-10-18 09:45:48',
            ],
            [
                'uuid' => '01K7VBDFZX2EQMD208M9DTX06M',
                'user_id' => $user->id,
                'label' => 'Classic White Cotton Shirt',
                'category' => 'top',
                'occasion' => 'business',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#FFFFFF']),
                'source_path' => 'source/1/ad19f2e3-832e-4cb0-8561-3d417c1159fb.png',
                'image_path' => 'wardrobe/1/11.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A timeless white long-sleeved shirt crafted from premium cotton, offering a crisp and versatile look for any professional or smart-casual setting. Its minimalist design ensures effortless styling and enduring elegance.', 'materials' => ['cotton']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:46:35',
                'updated_at' => '2025-10-18 09:46:35',
            ],
            [
                'uuid' => '01K7VBECAFRRVQB8V3TPWWX4CN',
                'user_id' => $user->id,
                'label' => 'Adidas Gazelle-Inspired Sneakers',
                'category' => 'shoes',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#FFFFFF', 'secondary' => '#C8C8C8']),
                'source_path' => 'source/1/b33c52a8-380c-4e6e-8ddd-c59e6a351852.jpeg',
                'image_path' => 'wardrobe/1/12.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Step out in classic style with these clean white sneakers featuring a suede toe cap and iconic three stripes. Perfect for everyday wear, offering comfort and timeless appeal.', 'materials' => ['leather', 'suede', 'rubber']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'Wipe clean with a damp cloth', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:47:04',
                'updated_at' => '2025-10-18 09:47:04',
            ],
            [
                'uuid' => '01K7VBFV4T87G8TZ2EAB2C8WBQ',
                'user_id' => $user->id,
                'label' => 'Classic White Cotton Shirt',
                'category' => 'top',
                'occasion' => 'business',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#FFFFFF']),
                'source_path' => 'source/1/461414db-e5ef-48f6-b75f-5da9911b71a7.png',
                'image_path' => 'wardrobe/1/13.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A timeless white cotton shirt, perfect for a polished and professional look. Its crisp design ensures versatility for various business occasions.', 'materials' => ['cotton']]),
                'metadata' => json_encode(['fit' => 'tailored', 'pattern' => 'solid', 'care' => 'machine wash cold, tumble dry low', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:47:52',
                'updated_at' => '2025-10-18 09:47:52',
            ],
            [
                'uuid' => '01K7VBGTVX1F5HHZWPX3YVBJKC',
                'user_id' => $user->id,
                'label' => 'Untitled garment',
                'category' => null,
                'occasion' => null,
                'season' => null,
                'color_palette' => null,
                'source_path' => 'source/1/da998027-50ed-4dd6-8e34-b0aef9f1f462.png',
                'image_path' => 'wardrobe/1/14.png',
                'thumbnail_path' => null,
                'ai_summary' => null,
                'metadata' => json_encode(['fit' => null, 'pattern' => null, 'care' => null, 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:48:25',
                'updated_at' => '2025-10-18 09:48:25',
            ],
            [
                'uuid' => '01K7VBJZWY9E2XWZS9AAE0M6YA',
                'user_id' => $user->id,
                'label' => 'Buckled Suede Clogs',
                'category' => 'shoes',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#C6B296', 'secondary' => '#7D7B7A']),
                'source_path' => 'source/1/2483ca9a-491c-4e33-83d7-897649ff6e3e.png',
                'image_path' => 'wardrobe/1/15.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Step out in style and comfort with these chic suede clogs, featuring a distinctive buckled strap for a touch of modern flair.', 'materials' => ['suede', 'cork', 'rubber']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'null', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:49:36',
                'updated_at' => '2025-10-18 09:49:36',
            ],
            [
                'uuid' => '01K7VBKJB29004SG7WXP0G25CW',
                'user_id' => $user->id,
                'label' => 'Platform Combat Boots',
                'category' => 'shoes',
                'occasion' => 'casual',
                'season' => 'autumn',
                'color_palette' => json_encode(['primary' => '#0A0A0A']),
                'source_path' => 'source/1/6e49e13d-4ad6-4cc7-aa17-a2394aaacdfe.png',
                'image_path' => 'wardrobe/1/16.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'Step up your style game with these edgy platform combat boots, featuring a sturdy design perfect for making a bold fashion statement. Their robust construction ensures durability while adding a rebellious touch to any outfit.', 'materials' => ['faux leather', 'rubber sole']]),
                'metadata' => json_encode(['fit' => null, 'pattern' => 'solid', 'care' => 'wipe clean', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:49:54',
                'updated_at' => '2025-10-18 09:49:54',
            ],
            [
                'uuid' => '01K7VBM9RC2N8MVBCG7KW6NSDD',
                'user_id' => $user->id,
                'label' => 'Cropped Button-Front Cardigan',
                'category' => 'outerwear',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#D3D3D3']),
                'source_path' => 'source/1/6026e441-3d9f-4738-8197-3bf4c9434678.png',
                'image_path' => 'wardrobe/1/17.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A versatile light grey cropped cardigan, perfect for layering over various outfits for a touch of warmth and style.', 'materials' => ['knit fabric']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'null', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:50:18',
                'updated_at' => '2025-10-18 09:50:18',
            ],
            [
                'uuid' => '01K7VBMXMC96990Z7NRVYQWTHN',
                'user_id' => $user->id,
                'label' => 'Crewneck Cashmere Sweater',
                'category' => 'top',
                'occasion' => 'casual',
                'season' => 'autumn',
                'color_palette' => json_encode(['primary' => '#A9A9A9']),
                'source_path' => 'source/1/f89ed86d-5394-4c68-9e90-8ab115617de9.png',
                'image_path' => 'wardrobe/1/18.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A versatile and comfortable crewneck sweater, perfect for adding a touch of casual elegance to any outfit. Its soft texture makes it ideal for cooler weather.', 'materials' => ['cashmere']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'dry clean only', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:50:39',
                'updated_at' => '2025-10-18 09:50:39',
            ],
            [
                'uuid' => '01K7VBNJ2V1WBMWP7DQ11RGSEZ',
                'user_id' => $user->id,
                'label' => 'Wide-Leg Dark Wash Jeans',
                'category' => 'bottom',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#1A2333', 'secondary' => '#FFFF00']),
                'source_path' => 'source/1/0e024e0c-bfb0-4b12-b662-781426992f9a.png',
                'image_path' => 'wardrobe/1/19.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'These stylish wide-leg jeans offer a comfortable yet fashionable silhouette in a versatile dark wash, perfect for elevating any casual look. Crafted from durable denim, they feature contrasting yellow stitching that adds a touch of classic appeal.', 'materials' => ['Denim', 'Cotton']]),
                'metadata' => json_encode(['fit' => 'relaxed', 'pattern' => 'solid', 'care' => 'Machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:51:00',
                'updated_at' => '2025-10-18 09:51:00',
            ],
            [
                'uuid' => '01K7VBP958KT5R9MC7AXXFMWV4',
                'user_id' => $user->id,
                'label' => 'Untitled garment',
                'category' => null,
                'occasion' => null,
                'season' => null,
                'color_palette' => null,
                'source_path' => 'source/1/e97d4d39-a76e-456a-abef-52a0b3f73901.png',
                'image_path' => 'wardrobe/1/20.png',
                'thumbnail_path' => null,
                'ai_summary' => null,
                'metadata' => json_encode(['fit' => null, 'pattern' => null, 'care' => null, 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:51:23',
                'updated_at' => '2025-10-18 09:51:23',
            ],
            [
                'uuid' => '01K7VBPVVGY9XH50TEDDTSY2NW',
                'user_id' => $user->id,
                'label' => 'Essential Long Sleeve Crew Neck Top',
                'category' => 'top',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#1A1A1A']),
                'source_path' => 'source/1/cc27b26f-2682-4509-a4d1-0dc1ffe30b21.png',
                'image_path' => 'wardrobe/1/21.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'This versatile black long-sleeve top is a wardrobe essential, offering a sleek and comfortable fit for everyday wear. Crafted from a soft, stretchable fabric, it\'s perfect for layering or wearing on its own.', 'materials' => ['cotton blend', 'elastane']]),
                'metadata' => json_encode(['fit' => 'slim', 'pattern' => 'solid', 'care' => 'machine wash cold, tumble dry low', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:51:42',
                'updated_at' => '2025-10-18 09:51:42',
            ],
            [
                'uuid' => '01K7VBR4EJQH5EPX0976T1NC7W',
                'user_id' => $user->id,
                'label' => 'Classic Black Leather Biker Jacket',
                'category' => 'outerwear',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#000000', 'secondary' => '#A9A9A9']),
                'source_path' => 'source/1/3d6e18c1-7b8e-4220-9ebf-4a5e8f457209.jpeg',
                'image_path' => 'wardrobe/1/22.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A timeless black leather biker jacket, perfect for adding an edgy touch to any outfit. Featuring classic details like an asymmetrical zip closure and silver-tone hardware.', 'materials' => ['leather']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'Specialist leather clean', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:52:24',
                'updated_at' => '2025-10-18 09:52:24',
            ],
            [
                'uuid' => '01K7VBSZ3QBW2R7GQYMTSBJZKW',
                'user_id' => $user->id,
                'label' => 'Navy Blue Pleated Trousers',
                'category' => 'bottom',
                'occasion' => 'business',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#2D3748']),
                'source_path' => 'source/1/066d977b-eaa8-4bf4-9df4-89384aa8be6e.jpeg',
                'image_path' => 'wardrobe/1/23.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'These elegant navy blue pleated trousers offer a sophisticated and comfortable fit, perfect for professional settings. Crafted with attention to detail, they provide a polished look for any business occasion.', 'materials' => ['polyester blend']]),
                'metadata' => json_encode(['fit' => 'tailored', 'pattern' => 'solid', 'care' => 'dry clean', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:53:24',
                'updated_at' => '2025-10-18 09:53:24',
            ],
            [
                'uuid' => '01K7VBXQNBHCA9TPBVQD1J80FR',
                'user_id' => $user->id,
                'label' => 'High-Waist Straight Leg Jeans',
                'category' => 'bottom',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#A6D2EE']),
                'source_path' => 'source/1/039c65e8-9c22-49c6-81d8-d3be5cc7e4a3.jpeg',
                'image_path' => 'wardrobe/1/24.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'These high-waisted, straight-leg jeans offer a timeless and versatile look, perfect for everyday wear.', 'materials' => ['denim', 'cotton']]),
                'metadata' => json_encode(['fit' => 'regular', 'pattern' => 'solid', 'care' => 'Machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:55:28',
                'updated_at' => '2025-10-18 09:55:28',
            ],
            [
                'uuid' => '01K7VBZDNK6Q3T0EMSA36HT68W',
                'user_id' => $user->id,
                'label' => 'Soft Green V-Neck Cardigan',
                'category' => 'top',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#B2E0B2', 'secondary' => '#8B8D70']),
                'source_path' => 'source/1/c5111ae2-86bb-4b25-ad43-27ee3ecc7ba5.jpeg',
                'image_path' => 'wardrobe/1/25.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A cozy and versatile soft green cardigan, perfect for layering over various outfits for a touch of warmth and casual style.', 'materials' => ['knitted fabric', 'buttons']]),
                'metadata' => json_encode(['fit' => 'relaxed', 'pattern' => 'solid', 'care' => null, 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:56:23',
                'updated_at' => '2025-10-18 09:56:23',
            ],
            [
                'uuid' => '01K7VC04JPC9RR4D88KA60CMB5',
                'user_id' => $user->id,
                'label' => 'Cropped Dusty Pink Hoodie',
                'category' => 'top',
                'occasion' => 'casual',
                'season' => 'all-season',
                'color_palette' => json_encode(['primary' => '#C68E82']),
                'source_path' => 'source/1/0acd8078-8d8b-4d34-994a-891710363f8e.jpeg',
                'image_path' => 'wardrobe/1/26.png',
                'thumbnail_path' => null,
                'ai_summary' => json_encode(['description' => 'A comfortable and stylish dusty pink cropped hoodie, perfect for adding a touch of laid-back chic to your everyday look.', 'materials' => ['cotton blend']]),
                'metadata' => json_encode(['fit' => 'relaxed', 'pattern' => 'solid', 'care' => 'machine wash cold', 'ingestion_status' => 'completed']),
                'is_favorite' => 0,
                'last_used_at' => null,
                'deleted_at' => null,
                'created_at' => '2025-10-18 09:56:46',
                'updated_at' => '2025-10-18 09:56:46',
            ],
        ];

        DB::table('clothes')->insert($clothes);
    }
}
